chore: Separate logs dump on tests failure into own step
Separate test action log output into multiple steps,
in order to simplify spotting the failure:

* Warmup tests
  This step hides useless deps installation and docker pull logs

* Run tests
  This step contains useful logs and should be checked on tests failure.

* Server logs
  This step is executed on "Run tests" step failure and can be used
  for deeper debugging of the failure.

* Check tests status
  This step fails the action if "Run tests" is not successful

This diff also updates Go installation scripts to use v1.20

The tigrisdata/tigris-build-base docker image has been updated to
include Go 1.20 too.

diff --git a/.github/workflows/go-test.yaml b/.github/workflows/go-test.yaml
--- a/.github/workflows/go-test.yaml
+++ b/.github/workflows/go-test.yaml
@@ -17,10 +17,26 @@ jobs:
         with:
           submodules: true
 
+      # this is just to separate deps and docker pull logs from the main tests step
+      - name: Warmup tests
+        run: make run
+
       - name: Run tests
-        run: make test || ( docker-compose -f test/docker/docker-compose.yml logs && false )
+        id: tests
+        run: make test
+        continue-on-error: true
         env:
           TEST_PARAM: "-coverprofile=coverage.out -covermode=atomic"
+
+      - name: Server logs
+        if: steps.tests.outcome != 'success'
+        run: docker-compose -f test/docker/docker-compose.yml logs
+
+      - name: Check tests status
+        if: steps.tests.outcome != 'success'
+        run: |
+          echo "^^ Tests failed. Check tests output and logs in the steps above ^^"
+          exit 1
 
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v3
